import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({
  baseDirectory: import.meta.dirname,
});

const eslintConfig = [
  // next-env.d.ts is generated by Next on every build (and gitignored), and its triple-slash
  // reference trips next/typescript's own rule - so `npm run lint` failed on a file nobody
  // writes. .next/ and node_modules/ are build output for the same reason.
  { ignores: [".next/**", "node_modules/**", "next-env.d.ts"] },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
];

export default eslintConfig;
