/**
 * name -> Simple Icons (cdn.simpleicons.org) slug, for SkillTag's automatic icon lookup.
 * Add an entry here once and every SKILLS/CAREER tag list that uses that name (any casing/
 * spacing variant listed) picks up the icon automatically. Names not listed here just render
 * as a plain tag — that's expected, not a bug.
 */
export const SKILL_ICON_SLUGS: Record<string, string> = {
  react: "react",
  "react.js": "react",
  reactjs: "react",
  "react native": "react",
  "react-native": "react",
  "next.js": "nextdotjs",
  nextjs: "nextdotjs",
  typescript: "typescript",
  javascript: "javascript",
  "vue.js": "vuedotjs",
  vue: "vuedotjs",
  "node.js": "nodedotjs",
  nodejs: "nodedotjs",
  node: "nodedotjs",
  expo: "expo",
  flutter: "flutter",
  swift: "swift",
  kotlin: "kotlin",
  java: "openjdk",
  python: "python",
  php: "php",
  html: "html5",
  html5: "html5",
  css: "css3",
  css3: "css3",
  "tailwind css": "tailwindcss",
  tailwindcss: "tailwindcss",
  sass: "sass",
  graphql: "graphql",

  docker: "docker",
  kubernetes: "kubernetes",
  "github actions": "githubactions",
  githubactions: "githubactions",
  aws: "amazonaws",
  "amazon web services": "amazonaws",
  "aws s3": "amazonaws",
  "aws ec2": "amazonaws",
  vercel: "vercel",
  netlify: "netlify",
  nginx: "nginx",
  linux: "linux",
  terraform: "terraform",
  jenkins: "jenkins",

  mongodb: "mongodb",
  postgresql: "postgresql",
  postgres: "postgresql",
  mysql: "mysql",
  sqlite: "sqlite",
  redis: "redis",
  firebase: "firebase",
  supabase: "supabase",
  "spring boot": "springboot",
  springboot: "springboot",
  fastapi: "fastapi",
  express: "express",

  git: "git",
  github: "github",
  gitlab: "gitlab",
  figma: "figma",
  jest: "jest",
  eslint: "eslint",
  webpack: "webpack",
  vite: "vite",
  notion: "notion",
  swagger: "swagger",
  bootstrap: "bootstrap",
  axios: "axios",
  "socket.io": "socketdotio",
  "react query": "reactquery",
  "tanstack query": "reactquery",
  "react-hook-form": "reacthookform",
  "react hook form": "reacthookform",
};

export function normalizeSkillName(name: string): string {
  return name.trim().toLowerCase();
}
